server:
  port: 9091
  servlet:
    context-path: /up
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 50MB